package com.reqman.pojo;

// Generated 9 Nov, 2017 10:10:33 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", uniqueConstraints = @UniqueConstraint(columnNames = "organizationkey"))
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5568463467860525430L;
	private int id;
	private String name;
	private Boolean status;
	private Date datecreated;
	private String createdby;
	private byte[] photo;
	private String imagename;
private String organizationkey;

	private Set<Users> userses = new HashSet<Users>(0);

	public Account() {
	}

	public Account(int id) {
		this.id = id;
	}

	

	public Account(int id, String name, Boolean status, Date datecreated, String createdby, byte[] photo,
			String imagename, String organizationkey, Set<Users> userses) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.datecreated = datecreated;
		this.createdby = createdby;
		this.photo = photo;
		this.imagename = imagename;
		this.organizationkey = organizationkey;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name",  length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "createdby", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "logo")
	public byte[] getPhoto() {
		return photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	
	@Column(name = "imagename", length = 100)
	public String getImagename() {
		return imagename;
	}

	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@Column(name = "organizationkey",unique = true, length = 100)
	public String getOrganizationkey() {
		return organizationkey;
	}

	public void setOrganizationkey(String organizationkey) {
		this.organizationkey = organizationkey;
	}

	
	
	
}
