package com.reqman.pojo;

// Generated 22 Aug, 2017 7:11:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name = "accountusers", uniqueConstraints = @UniqueConstraint(columnNames = {
		"accountid", "userid" }))
public class Accountusers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7805396446530244069L;
	private int id;
	private Account account;
	private Users users;
	private Boolean imagestatus;

	public Accountusers() {
	}

	public Accountusers(int id) {
		this.id = id;
	}

	public Accountusers(int id, Account account, Users users,Boolean imagestatus) {
		this.id = id;
		this.account = account;
		this.users = users;
		this.imagestatus=imagestatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountid")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	@Column(name = "imagestatus")
	public Boolean getImagestatus() {
		return imagestatus;
	}

	public void setImagestatus(Boolean imagestatus) {
		this.imagestatus = imagestatus;
	}

	
	
	
}
