package com.reqman.pojo;

// Generated 18 Jan, 2018 11:02:49 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customerpayment generated by hbm2java
 */
@Entity
@Table(name = "customerpayment")
public class Customerpayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6057893830017330724L;
	private long id;
	private Users users;
	private String productname;
	private Long productid;
	private String subscriptionname;
	private Long subscriptionid;
	private Long customerid;
	private Date currenttermstartat;
	private Date currenttermend;
	private Boolean status;
	private Date createdon;

	public Customerpayment() {
	}

	public Customerpayment(long id) {
		this.id = id;
	}

	public Customerpayment(long id, Users users, String productname,
			Long productid, String subscriptionname, Long subscriptionid,
			Long customerid, Date currenttermstartat, Date currenttermend,
			Boolean status, Date createdon) {
		this.id = id;
		this.users = users;
		this.productname = productname;
		this.productid = productid;
		this.subscriptionname = subscriptionname;
		this.subscriptionid = subscriptionid;
		this.customerid = customerid;
		this.currenttermstartat = currenttermstartat;
		this.currenttermend = currenttermend;
		this.status = status;
		this.createdon = createdon;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "productname", length = 200)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "productid")
	public Long getProductid() {
		return this.productid;
	}

	public void setProductid(Long productid) {
		this.productid = productid;
	}

	@Column(name = "subscriptionname", length = 200)
	public String getSubscriptionname() {
		return this.subscriptionname;
	}

	public void setSubscriptionname(String subscriptionname) {
		this.subscriptionname = subscriptionname;
	}

	@Column(name = "subscriptionid")
	public Long getSubscriptionid() {
		return this.subscriptionid;
	}

	public void setSubscriptionid(Long subscriptionid) {
		this.subscriptionid = subscriptionid;
	}

	@Column(name = "customerid")
	public Long getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Long customerid) {
		this.customerid = customerid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "currenttermstartat", length = 13)
	public Date getCurrenttermstartat() {
		return this.currenttermstartat;
	}

	public void setCurrenttermstartat(Date currenttermstartat) {
		this.currenttermstartat = currenttermstartat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "currenttermend", length = 13)
	public Date getCurrenttermend() {
		return this.currenttermend;
	}

	public void setCurrenttermend(Date currenttermend) {
		this.currenttermend = currenttermend;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 35)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

}
