package com.reqman.pojo;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * generated by hbm2java
 *
 */

@Entity
@Table(name = "organisationdetails")
public class Organisationdetails  implements java.io.Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4955089052960189841L;
	
	private int id;
	private String organisationname;
	private Date createdon;
	private String createdby;
	private String updatedby;
	private Date updatedon;
	private Boolean status;
	
   public Organisationdetails() {
		
		// TODO Auto-generated constructor stub
	}

	
	public Organisationdetails(int id) {		
		this.id = id;
	}


	public Organisationdetails(int id, String organisationname, Date createdon,
			String createdby, String updatedby, Date updatedon, boolean status) {
		super();
		this.id = id;
		this.organisationname = organisationname;
		this.createdon = createdon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.updatedon = updatedon;
		this.status = status;
	}

	@Id
	 @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "organisationname", length = 100)
	public String getOrganisationname() {
		return organisationname;
	}


	public void setOrganisationname(String organisationname) {
		this.organisationname = organisationname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 29)
	public Date getCreatedon() {
		return createdon;
	}


	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "createdby", length = 100)
	public String getCreatedby() {
		return createdby;
	}


	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", length = 100)
	public String getUpdatedby() {
		return updatedby;
	}


	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 29)
	public Date getUpdatedon() {
		return updatedon;
	}


	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return status;
	}


	public void setStatus(Boolean status) {
		this.status = status;
	}

	

}
