package com.reqman.pojo;

// Generated 29 Jan, 2018 9:47:44 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicemaildomains generated by hbm2java
 */
@Entity
@Table(name = "publicemaildomains")
public class Publicemaildomains implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5949459845138594524L;
	private long id;
	private String name;
	private Boolean status;
	private Date datecreated;
	private String createdby;

	public Publicemaildomains() {
	}

	public Publicemaildomains(long id) {
		this.id = id;
	}

	public Publicemaildomains(long id, String name, Boolean status,
			Date datecreated, String createdby) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.datecreated = datecreated;
		this.createdby = createdby;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "createdby", length = 20)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

}
