package com.reqman.pojo;

// Generated 22 Aug, 2017 7:11:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Requesttype generated by hbm2java
 */
@Entity
@Table(name = "requesttype", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Requesttype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5895790308046424626L;
	private int id;
	private String name;
	private Boolean status;
	private Date datecreated;
	private String createdby;
	private Set<Userrequesttype> userrequesttypes = new HashSet<Userrequesttype>(
			0);

	public Requesttype() {
	}

	public Requesttype(int id) {
		this.id = id;
	}

	public Requesttype(int id, String name, Boolean status, Date datecreated,
			String createdby, Set<Userrequesttype> userrequesttypes) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.datecreated = datecreated;
		this.createdby = createdby;
		this.userrequesttypes = userrequesttypes;
	}

	@Id
	 @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requesttype")
	public Set<Userrequesttype> getUserrequesttypes() {
		return this.userrequesttypes;
	}

	public void setUserrequesttypes(Set<Userrequesttype> userrequesttypes) {
		this.userrequesttypes = userrequesttypes;
	}

}
