package com.reqman.pojo;

// Generated 6 Nov, 2017 3:40:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requestnotes generated by hbm2java
 */
@Entity
@Table(name = "requestnotes")
public class Requestnotes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2996722310879521420L;
	private int id;
	private Request request;
	private String description;
	private String createdby;
	private Date createdon;

	public Requestnotes() {
	}

	public Requestnotes(int id) {
		this.id = id;
	}

	public Requestnotes(int id, Request request, String description,
			String createdby, Date createdon) {
		this.id = id;
		this.request = request;
		this.description = description;
		this.createdby = createdby;
		this.createdon = createdon;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "requestid")
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

}
