package com.reqman.pojo;

// Generated 6 Nov, 2017 3:40:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requestnotes generated by hbm2java
 */
@Entity
@Table(name = "requestnotes")
public class Requestnotes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2996722310879521420L;
	private int id;
	private Request request;
	private String message;
	private String createdby;
	private Date createdon;
	private Boolean requeststatus;
	private Boolean teammemberstatus;
	
	public Requestnotes() {
	}

	public Requestnotes(int id) {
		this.id = id;
	}

	public Requestnotes(int id, Request request, String message,
			String createdby, Date createdon,Boolean requeststatus,Boolean teammemberstatus) {
		this.id = id;
		this.request = request;
		this.message = message;
		this.createdby = createdby;
		this.createdon = createdon;
		this.requeststatus =requeststatus;
		this.teammemberstatus = teammemberstatus;
	}

	@Id
	 @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "requestid")
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	@Column(name = "message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}
	@Column(name = "requeststatus")
	public Boolean getRequeststatus() {
		return requeststatus;
	}

	public void setRequeststatus(Boolean requeststatus) {
		this.requeststatus = requeststatus;
	}
	@Column(name = "teammemberstatus")
	public Boolean getTeammemberstatus() {
		return teammemberstatus;
	}

	public void setTeammemberstatus(Boolean teammemberstatus) {
		this.teammemberstatus = teammemberstatus;
	}

	
	
}
