package com.reqman.pojo;

// Generated 22 Aug, 2017 7:11:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name = "userroles", uniqueConstraints = @UniqueConstraint(columnNames = {
		"roleid", "userid" }))
public class Userroles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7805396446530244069L;
	private int id;
	private Roles roles;
	private Users users;

	public Userroles() {
	}

	public Userroles(int id) {
		this.id = id;
	}

	public Userroles(int id, Roles roles, Users users) {
		this.id = id;
		this.roles = roles;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
