package com.reqman.pojo;

// Generated 20 Jul, 2017 1:31:34 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.reqman.common.HibernateSessionFactory;
import com.reqman.common.HibernateUtilH;

/**
 * Users generated by hbm2java
 */
@ManagedBean
@SessionScoped
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4926486795490835056L;
	private String emailid;
	private String password;
	private String firstname;
	private String lastname;
	private String groupname;
	private Boolean status;
	private String createdby;
	

	public Users() {
	}

	public Users(String emailid) {
		this.emailid = emailid;
	}

	public Users(String emailid, String password, String firstname,
			String lastname, String groupname, Boolean status,
			String createdby) {
		this.emailid = emailid;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.groupname = groupname;
		this.status = status;
		this.createdby = createdby;
	//	this.createdon = createdon;
	//	this.lastlogin = lastlogin;
	}

	@Id
	@Column(name = "emailid", unique = true, nullable = false, length = 100)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "groupname", length = 45)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "createdby", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	
	public String submit(){	
		  Session session; 
	    String result=null;
	    SessionFactory hsf = HibernateUtilH.getSessionFactory();
      session = hsf.openSession();	
		try{
			//create a student object			
		this.setFirstname(firstname);
		this.setLastname(lastname);
		this.setEmailid(emailid);
		this.setPassword(password);
		this.setGroupname(groupname);
		this.setStatus(status);
		this.setCreatedby(createdby);
	//	this.setCreatedon(createdon);
	//	this.setLastlogin(lastlogin);
			
			//start a transaction 
			session.beginTransaction();
			//save the student object			
	result=(String)	session.save(this);
			//commit transaction
			session.getTransaction().commit();
			System.out.println("done");
			if(result!=null){
				return "login.xhtml";
			}else{
				FacesContext.getCurrentInstance().addMessage(
						null,
						new FacesMessage(FacesMessage.SEVERITY_WARN,
								"AlreadyExist register",
								"Please Enter a another_name"));
				return "register.xhtml";
			}			
		}	catch(Exception e){
			System.out.print(e);
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_WARN,
							"AlreadyExist register",
							"Please Enter a another_name"));
			return "index.xhtml";
		}
			
      }

	
	}
	
	




